export { default as AdminLogin } from './AdminLogin';
export { default as AdminDashboard } from './AdminDashboard';
export { default as ReservationsManagement } from './ReservationsManagement';
export { default as EmployeesManagement } from './EmployeesManagement';
export { default as ServicesManagement } from './ServicesManagement';
export { default as CalendarManagement } from './CalendarManagement';
export { default as Reports } from './Reports';
export { default as Settings } from './Settings';
export { default as SalonSignup } from './SalonSignup'; 